#ifndef GUARD_CONSTANTS_GAME_STAT_H
#define GUARD_CONSTANTS_GAME_STAT_H

#define GAME_STAT_SAVED_GAME                 0
#define GAME_STAT_FIRST_HOF_PLAY_TIME        1
#define GAME_STAT_UNUSED_2                   2
#define GAME_STAT_PLANTED_BERRIES            3
#define GAME_STAT_TRADED_BIKES               4
#define GAME_STAT_STEPS                      5
#define GAME_STAT_UNUSED_6                   6
#define GAME_STAT_TOTAL_BATTLES              7
#define GAME_STAT_WILD_BATTLES               8
#define GAME_STAT_TRAINER_BATTLES            9
#define GAME_STAT_UNUSED_10                 10
#define GAME_STAT_POKEMON_CAPTURES          11
#define GAME_STAT_FISHING_CAPTURES          12
#define GAME_STAT_HATCHED_EGGS              13
#define GAME_STAT_EVOLVED_POKEMON           14
#define GAME_STAT_USED_POKECENTER           15
#define GAME_STAT_RESTED_AT_HOME            16
#define GAME_STAT_UNUSED_17                 17
#define GAME_STAT_USED_CUT                  18
#define GAME_STAT_USED_ROCK_SMASH           19
#define GAME_STAT_UNUSED_20                 20
#define GAME_STAT_UNUSED_21                 21
#define GAME_STAT_UNUSED_22                 22
#define GAME_STAT_UNUSED_23                 23
#define GAME_STAT_UNUSED_24                 24
#define GAME_STAT_UNUSED_25                 25
#define GAME_STAT_USED_SPLASH               26
#define GAME_STAT_USED_STRUGGLE             27
#define GAME_STAT_UNUSED_28                 28
#define GAME_STAT_UNUSED_29                 29
#define GAME_STAT_UNUSED_30                 30
#define GAME_STAT_UNUSED_31                 31
#define GAME_STAT_UNUSED_32                 32
#define GAME_STAT_UNUSED_33                 33
#define GAME_STAT_UNUSED_34                 34
#define GAME_STAT_UNUSED_35                 35
#define GAME_STAT_UNUSED_36                 36
#define GAME_STAT_UNUSED_37                 37
#define GAME_STAT_SHOPPED                   38
#define GAME_STAT_UNUSED_39                 39
#define GAME_STAT_GOT_RAINED_ON             40
#define GAME_STAT_CHECKED_POKEDEX           41
#define GAME_STAT_UNUSED_42                 42
#define GAME_STAT_JUMPED_DOWN_LEDGES        43
#define GAME_STAT_UNUSED_44                 44
#define GAME_STAT_UNUSED_45                 45
#define GAME_STAT_UNUSED_46                 46
#define GAME_STAT_USED_DAYCARE              47
#define GAME_STAT_UNUSED_48                 48
#define GAME_STAT_UNUSED_49                 49
#define GAME_STAT_UNUSED_50                 50
#define GAME_STAT_DEXNAV_SCANNED            51

#define NUM_USED_GAME_STATS                 52
#define NUM_GAME_STATS                      64

#endif // GUARD_CONSTANTS_GAME_STAT_H
