	.align 2
gText_ConfirmSave::
	.string "¿Te gustaría guardar?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobreescribirla?$"

gText_SavingDontTurnOff::
	.string "Guardando…\n"
	.string "No apagues la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "Cuidado.\p"
	.string "Hay otra partida guardada.\n"
	.string "Si guardas, la otra partida se borrará.\p"
	.string "¿Estás seguro?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "Guardando…\n"
	.string "No apagues la consola.$"
