EverGrandeCity_SidneysRoom_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, EverGrandeCity_SidneysRoom_OnLoad
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, EverGrandeCity_SidneysRoom_OnWarp
	map_script MAP_SCRIPT_ON_TRANSITION, EverGrandeCity_SidneysRoom_OnTransition
	map_script MAP_SCRIPT_ON_FRAME_TABLE, EverGrandeCity_SidneysRoom_OnFrame
	.byte 0

EverGrandeCity_SidneysRoom_OnTransition:
	setflag FLAG_MET_SCOTT_IN_EVERGRANDE
	setflag FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT
	end

EverGrandeCity_SidneysRoom_OnLoad:
	call_if_set FLAG_DEFEATED_ELITE_4_SIDNEY, EverGrandeCity_SidneysRoom_EventScript_ResetAdvanceToNextRoom
	call_if_eq VAR_ELITE_4_STATE, 1, EverGrandeCity_SidneysRoom_EventScript_CloseDoor
	end

EverGrandeCity_SidneysRoom_EventScript_ResetAdvanceToNextRoom::
	call PokemonLeague_EliteFour_EventScript_ResetAdvanceToNextRoom
	return

EverGrandeCity_SidneysRoom_EventScript_CloseDoor::
	call PokemonLeague_EliteFour_EventScript_CloseDoor
	return

EverGrandeCity_SidneysRoom_OnWarp:
	map_script_2 VAR_TEMP_1, 0, EverGrandeCity_SidneysRoom_EventScript_PlayerTurnNorth
	.2byte 0

EverGrandeCity_SidneysRoom_EventScript_PlayerTurnNorth::
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	end

EverGrandeCity_SidneysRoom_OnFrame:
	map_script_2 VAR_ELITE_4_STATE, 0, EverGrandeCity_SidneysRoom_EventScript_WalkInCloseDoor
	.2byte 0

EverGrandeCity_SidneysRoom_EventScript_WalkInCloseDoor::
	lockall
	call PokemonLeague_EliteFour_EventScript_WalkInCloseDoor
	setvar VAR_ELITE_4_STATE, 1
	releaseall
	end

EverGrandeCity_SidneysRoom_EventScript_Sidney::
	lock
	faceplayer
	goto_if_ge VAR_POKEMON_LEAGUE_RUNS_COUNTER, 1, EverGrandeCity_SidneysRoom_EventScript_SidneyRematch
	goto_if_set FLAG_DEFEATED_ELITE_4_SIDNEY, EverGrandeCity_SidneysRoom_EventScript_PostBattleSpeech
	playbgm MUS_ENCOUNTER_ELITE_FOUR, FALSE
	msgbox EverGrandeCity_SidneysRoom_Text_IntroSpeech, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_SIDNEY, EverGrandeCity_SidneysRoom_Text_Defeat
	goto EverGrandeCity_SidneysRoom_EventScript_Defeated
	end

EverGrandeCity_SidneysRoom_EventScript_PostBattleSpeech::
	msgbox EverGrandeCity_SidneysRoom_Text_PostBattleSpeech, MSGBOX_DEFAULT
	release
	end

EverGrandeCity_SidneysRoom_EventScript_Defeated::
	setflag FLAG_DEFEATED_ELITE_4_SIDNEY
	setflag FLAG_REMATCH_SIDNEY
	call PokemonLeague_EliteFour_SetAdvanceToNextRoomMetatiles
	msgbox EverGrandeCity_SidneysRoom_Text_PostBattleSpeech, MSGBOX_DEFAULT
	release
	end

EverGrandeCity_SidneysRoom_EventScript_SidneyRematch:
	goto_if_set FLAG_DEFEATED_ELITE_4_SIDNEY, EverGrandeCity_SidneysRoom_EventScript_PostRematchSpeech
	playbgm MUS_ENCOUNTER_ELITE_FOUR, FALSE
	call_if_ge VAR_POKEMON_LEAGUE_RUNS_COUNTER, 2, EverGrandeCity_SidneysRoom_EventScript_SidneyRematchIntro2
	call_if_eq VAR_POKEMON_LEAGUE_RUNS_COUNTER, 1, EverGrandeCity_SidneysRoom_EventScript_SidneyRematchIntro1
	trainerbattle_no_intro TRAINER_SIDNEY_REMATCH, EverGrandeCity_SidneysRoom_Text_DefeatRematch
	goto EverGrandeCity_SidneysRoom_EventScript_DefeatedRematch
	end

EverGrandeCity_SidneysRoom_EventScript_SidneyRematchIntro1:
	msgbox EverGrandeCity_SidneysRoom_Text_RematchIntroSpeech, MSGBOX_DEFAULT
	return

EverGrandeCity_SidneysRoom_EventScript_SidneyRematchIntro2:
	msgbox EverGrandeCity_SidneysRoom_Text_RematchIntroSpeech2, MSGBOX_DEFAULT
	return

EverGrandeCity_SidneysRoom_EventScript_PostRematchSpeech::
	msgbox EverGrandeCity_SidneysRoom_Text_PostRematchSpeech, MSGBOX_DEFAULT
	release
	end

EverGrandeCity_SidneysRoom_EventScript_DefeatedRematch:
	setflag FLAG_DEFEATED_ELITE_4_SIDNEY
	call PokemonLeague_EliteFour_SetAdvanceToNextRoomMetatiles
	msgbox EverGrandeCity_SidneysRoom_Text_PostRematchSpeech, MSGBOX_DEFAULT
	release
	end

EverGrandeCity_SidneysRoom_Text_IntroSpeech:
	.string "Welcome, challenger!\n"
	.string "I'm SIDNEY of the ELITE FOUR.\p"
	.string "I like that look you're giving me.\n"
	.string "I guess you'll give me a good match.\l"
	.string "That's good! Looking real good!\p"
	.string "All right! You and me, let's enjoy\n"
	.string "a battle that can only be staged\l"
	.string "here in the POKéMON LEAGUE!$"

EverGrandeCity_SidneysRoom_Text_Defeat:
	.string "Well, how do you like that? I lost!\n"
	.string "Eh, it was fun, so it doesn't matter.$"

EverGrandeCity_SidneysRoom_Text_PostBattleSpeech:
	.string "Well, listen to what this loser has\n"
	.string "to say.\p"
	.string "You've got what it takes to go far.\n"
	.string "Now, go on to the next room and enjoy\l"
	.string "your next battle!$"

EverGrandeCity_SidneysRoom_Text_RematchIntroSpeech:
	.string "Yo, champion! Welcome back!\n"
	.string "You're looking real good!\p"
	.string "If you're here, that means you\n"
	.string "want to take on the POKéMON LEAGUE\l"
	.string "challenge again, isn't that right?\p"
	.string "Heh heh… you better get ready then!\p"
	.string "Our new champion gave us artifacts\n"
	.string "called “KEY STONES”.\p"
	.string "They allow our POKéMON to perform an\n"
	.string "action called “MEGA EVOLUTION”, and\l"
	.string "that means we're crazy stronger!\p"
	.string "Let's do this, {PLAYER}!\n"
	.string "Let's have an excellent battle!$"

EverGrandeCity_SidneysRoom_Text_RematchIntroSpeech2:
	.string "Yo, champion! Welcome back!\n"
	.string "You're looking real good!\p"
	.string "If you're here, that means you\n"
	.string "want to take on the POKéMON LEAGUE\l"
	.string "challenge again, isn't that right?\p"
	.string "Come on then, let's have a battle\n"
	.string "that can only be staged here!$"

EverGrandeCity_SidneysRoom_Text_DefeatRematch:
	.string "Well, well, I lose again!$"

EverGrandeCity_SidneysRoom_Text_PostRematchSpeech:
	.string "Heh… you really are the strongest…\n"
	.string "Eh, I had fun, so whatever.\p"
	.string "Go on to the next room!\n"
	.string "Your next battle awaits!$"

